version: "3.9"
services:
    sql-server-db:
        container_name: sql-server-db
        image: "mcr.microsoft.com/mssql/server"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        volumes:
          - ./sql-server-db:/var/opt/mssql/data    
            ACCEPT_EULA: "Y"
